// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovblualoiyfapdlrsufk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92Ymx1YWxvaXlmYXBkbHJzdWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzE0NjAsImV4cCI6MjA2ODYwNzQ2MH0.yQiYaf_dkLHoOCsAh72oSlE3FMYuXUnwT0sq51pdg9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});